FROM node:lts as devcontainer
WORKDIR /root/chameleon-triangles/

RUN apt-get update && apt-get install -y git && apt-get install -y vim && apt-get update && apt install fish -y

COPY ../.devcontainer/devcontainer.json ./.devcontainer/devcontainer.json
COPY ../.devcontainer/docker-compose.yml ./.devcontainer/docker-compose.yml
COPY ../.devcontainer/Dockerfile.devcontainer ./.devcontainer/Dockerfile.devcontainer

